spring.application.name=websiteone

# Database Driver & Environment Variables
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate / JPA Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update